### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by Jamiepark816** [chenvict/dipm#4]
Hello, this is Jamie.

I'd like to validate a dipm model what I built. The outcomes of fitting model has solely split nodes, optimal treatment, and the number of observations. How can I get predicted survival probability of validation data in dipm package? Does it have any support to see predicted value for survival data?
Thanks. 

Best, 
Jamie

**Comment by chenvict** [comment]
Dear Jamie,

Thank you for your question!

Currently, the dipm package does not predict survival probabilities for
validation data.

The purpose of the method is to identify which treatment is optimal within
identified subgroups.

One could use the predict() function or write a custom function to separate
validation data into the identified subgroups and then perform prediction
for individual cases within subgroups using different survival models.

Or, one could calculate the median survival probabilities of the test data
within the identified subgroups.

Hope this helps!

Best,
Victoria

**Comment by Jamiepark816** [comment]
Thanks you for answer ! It really helps me a lot ◟̊◞̊

I have two questions more.

1. Referring your words, the different survival models for subgroups after building a final tree can be Cox PH model or survival regression, whatever?

2. According an example of dipm function, predict() function works for the data with continuous outcome variable, not for the survival outcome , right??

This is a prediction part of optimal treatment within confirmed subgroups.
# fit a dipm classification tree #
tree1=dipm(Y~treatment | .,data,mtry=1,maxdepth=3)
_**# predict optimal treatment for new subjects**_
predict(tree1, newdata=head(data), 
FUN = function(n)  as.numeric(n$info$opt_trt))


Best,
Jamie.

**Comment by chenvict** [comment]
Dear Jamie,

The dipm R package can work for data with right-censored survival outcomes
as well.

Thank you!

Best,
Victoria

**Comment by Jamiepark816** [comment]
Dear Victoria,

As my understanding, do you mean the predict() function to search optimal treatment also works for survival data? But, when i tried the code "n$info$opt_trt", it has an error .. How can i figure it out after fitting a tree with dipm() function?  
predict(tree1, newdata=head(data),
 FUN = function(n) as.numeric(n$info$opt_trt))

Take care!

Best,
Jamie.

**Comment by cli9** [comment]
You may refer to the partykit package since the returned object is a 'party' class. For example: predict(as.constparty(tree), newdata = head(data))
